# Generated by Django 4.1.3 on 2022-11-30 08:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='住所')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContractCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会社名')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='会社住所')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('president', models.CharField(blank=True, max_length=20, verbose_name='代表名')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='電話番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '契約会社',
            },
        ),
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='勤務開始時刻')),
                ('close_time', models.TimeField(verbose_name='勤務終了時刻')),
                ('start_break_time', models.TimeField(verbose_name='休憩開始時刻')),
                ('close_break_time', models.TimeField(verbose_name='休憩終了時刻')),
                ('start_overtime_break', models.TimeField(verbose_name='時間外休憩開始時刻')),
                ('close_overtime_break', models.TimeField(verbose_name='時間外休憩終了時刻')),
                ('round_down_unit', models.IntegerField(verbose_name='時間切捨単位')),
            ],
            options={
                'verbose_name': 'ワークパターン',
            },
        ),
        migrations.CreateModel(
            name='SalesPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='名')),
                ('last_name', models.CharField(max_length=10, verbose_name='氏')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Eメール')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=13, verbose_name='携帯電話番号')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_management_app.contractcompanies', verbose_name='契約会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '営業',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='プロジェクト名')),
                ('start_date', models.DateField(max_length=2, verbose_name='契約開始日')),
                ('last_date', models.DateField(max_length=2, verbose_name='契約終了日')),
                ('upper_work_hours', models.IntegerField(verbose_name='稼働上限時間')),
                ('lower_work_hours', models.IntegerField(verbose_name='稼働下限時間')),
                ('assigned_job', models.CharField(blank=True, max_length=50, verbose_name='担当業務')),
                ('summary', models.CharField(blank=True, max_length=100, verbose_name='概要')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_management_app.contractcompanies', verbose_name='契約会社')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'プロジェクト',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='年月日')),
                ('start_time', models.TimeField(verbose_name='勤務開始時刻')),
                ('close_time', models.TimeField(verbose_name='勤務終了時刻')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_management_app.projects', verbose_name='プロジェクト')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('work_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_management_app.workpattern', verbose_name='勤務パターン')),
            ],
            options={
                'verbose_name': '勤怠',
            },
        ),
        migrations.AddConstraint(
            model_name='salespeople',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'user', 'company'), name='salespeople_unique'),
        ),
        migrations.AddConstraint(
            model_name='contractcompanies',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='company_unique'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'user', 'project'), name='attendance_unique'),
        ),
    ]
