# Generated by Django 4.1.3 on 2022-11-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespeople',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='携帯電話番号'),
        ),
    ]
