# Generated by Django 4.1.3 on 2022-11-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0002_alter_salespeople_mobile_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('date', 'user', 'project'), name='attendance_unique'),
        ),
        migrations.AddConstraint(
            model_name='contractcompanies',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='company_unique'),
        ),
        migrations.AddConstraint(
            model_name='projects',
            constraint=models.UniqueConstraint(fields=('project_name', 'user', 'company'), name='project_unique'),
        ),
    ]
