# Generated by Django 4.1.3 on 2022-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_management_app', '0003_attendance_attendance_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractcompanies',
            options={'verbose_name': '契約会社'},
        ),
        migrations.AlterModelOptions(
            name='salespeople',
            options={'verbose_name': '営業'},
        ),
        migrations.AddConstraint(
            model_name='salespeople',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'user', 'company'), name='salespeople_unique'),
        ),
    ]
